app:
  instance:
    code: website
    profile: dev
server:
  port: 5000
logging:
  level:
    root: info
    com.bestvike: debug
    org.springframework.security: warn
spring:
  application:
    name: ${app.instance.code}-${app.instance.profile}
  http:
    encoding:
      force: true
  servlet:
    multipart:
      max-file-size: 20MB # 最大文件大小
      max-request-size: 20MB # 最大请求大小
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: LEGACYHTML5 # 用非严格的 HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
datasources:
  website:
    jdbc-url: jdbc:oracle:thin:@172.10.11.121:1521/orclgbk
    username: bvdf_qz
    password: bvdf_qz
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      connection-test-query: select 1